### ISSUE TITLE
Fix spacing on all HTML files

### ISSUE THREAD

**Issue by ZachSand** [brockuniera/cs373-idb#25]
Some of the template HTML files have non-uniform spacing, they should all conform to either 4 space indention or 2 space indention to make them more readable.

**Comment by ZachSand** [comment]
I personally prefer 2 space indention because of how verbose HTML is, but we can go with whatever the majority of the group prefers. Can you guys comment on your preference?
@tomasg2012 
@brockuniera 
@angelxut 
@annyuu

**Comment by brockuniera** [comment]
2 space
